# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
    config.vm.synced_folder "../data", "/vagrant_data"
    config.vm.define "ubuntuvm"

    config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
      # vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = 4096        # Memory size in M.
      vb.cpus   = 2           # Number of vCPUs
      vb.name   = "ubuntuvm"    # VM name.
      
      # Configure Graphics vmsvga controller 
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']

    end

    config.vm.provision "shell", path:"scripts/script.sh"
end
